package facebookapp;

import facebook4j.Facebook;
import facebook4j.FacebookException;
import facebook4j.FacebookFactory;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class is a JFrame class. That's the main class of the application
 *
 * @author Adri
 * @version 0.1.0
 * @since 05-27-2017
 */
public class Window extends javax.swing.JFrame {

    private Facebook facebook = new FacebookFactory().getInstance();

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method post a message on Facebook
     *
     * @author Adri
     * @version 0.1.0
     * @since 05-27-2017
     * @param mensaje
     */
    public void postMessage(String mensaje) {
        try {
            facebook.postStatusMessage(mensaje);
        } catch (FacebookException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method post a link with a title.
     *
     * @author Adri
     * @version 0.1.0
     * @since 05-27-2017
     * @param url
     * @param leyenda
     */
    public void postLink(URL url, String leyenda) {
        try {
            facebook.postLink(url, leyenda);
        } catch (FacebookException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        mensaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        link = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        leyendaLink = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonEstado = new javax.swing.JLabel();
        botonLink = new javax.swing.JLabel();
        barraLateral = new javax.swing.JPanel();
        iconoFacebook = new javax.swing.JLabel();
        botonFeed = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Post Link");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facebook");

        fondo.setBackground(new java.awt.Color(60, 90, 147));
        fondo.setForeground(new java.awt.Color(16, 79, 121));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Post Link");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Leyenda Link");

        botonEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voice-speaker (1).png"))); // NOI18N
        botonEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEstadoMouseClicked(evt);
            }
        });

        botonLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voice-speaker (1).png"))); // NOI18N
        botonLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLinkMouseClicked(evt);
            }
        });

        barraLateral.setBackground(new java.awt.Color(60, 90, 147));

        iconoFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook-circular-logo.png"))); // NOI18N
        iconoFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoFacebookMouseClicked(evt);
            }
        });

        botonFeed.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonFeed.setForeground(new java.awt.Color(255, 255, 255));
        botonFeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house-and-a-page-with-text (1).png"))); // NOI18N
        botonFeed.setText("  Feed");
        botonFeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonFeedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoFacebook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFeed, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoFacebook)
                .addGap(18, 18, 18)
                .addComponent(botonFeed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leyendaLink, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(link)
                            .addComponent(jLabel5)
                            .addComponent(mensaje))
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonLink)
                            .addComponent(botonEstado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(56, 56, 56))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEstado))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(botonLink))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leyendaLink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 147, Short.MAX_VALUE))
            .addComponent(barraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconoFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoFacebookMouseClicked


    }//GEN-LAST:event_iconoFacebookMouseClicked

    /**
     * Mouse clicked event to post the message.
     *
     * @author Adri
     * @version 0.1.0
     * @since 05-27-2017
     * @param evt
     */
    private void botonEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoMouseClicked
        postMessage(mensaje.getText());
        mensaje.setText(null);
    }//GEN-LAST:event_botonEstadoMouseClicked

    /**
     * Mouse clicked event to post a link.
     *
     * @author Adri
     * @version 0.1.0
     * @since 05-27-2017
     * @param evt
     */
    private void botonLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLinkMouseClicked
        try {
            URL url = new URL(link.getText());
            postLink(url, leyendaLink.getText());
            leyendaLink.setText(null);
            link.setText(null);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonLinkMouseClicked

    /**
     * Mouse clicked event to obtain the feed of the use.
     *
     * @author Adri
     * @version 0.1.0
     * @since 05-27-2017
     * @param evt
     */
    private void botonFeedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFeedMouseClicked
        FeedWindow feedW = new FeedWindow(facebook);
        feedW.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_botonFeedMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JLabel botonEstado;
    private javax.swing.JLabel botonFeed;
    private javax.swing.JLabel botonLink;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel iconoFacebook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField leyendaLink;
    private javax.swing.JTextField link;
    private javax.swing.JTextField mensaje;
    // End of variables declaration//GEN-END:variables
}
